FROM golang:1.20 as builder
RUN apt-get update && apt-get install -y libseccomp-dev
WORKDIR /go/src/app
COPY . .
RUN make build

FROM scratch
COPY --from=builder /go/src/app/kapprofiler /kapprofiler
ENTRYPOINT ["/kapprofiler"]

